<a href="https://colab.research.google.com/github/LuanFerreira3/Files/blob/main/Fase1_Aula_1_An%C3%A1lise_explorat%C3%B3ria_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ANALISANDO DADOS DE SAÚDE COMO PARTE DA AULA 1

In [3]:
import pandas as pd

In [10]:
import pandas as pd #1ª célula

dados = pd.read_csv('/content/A150850189_28_143_208.csv', encoding='ISO-8859-1', skiprows=3, sep=';', skipfooter=12, thousands='.', decimal=',') #2ª célula

dados.head()#3ª célula

dados.tail()#4ª célula

dados.info()#5ª célula

pd.options.display.float_format = '{:.2f}'.format #6ª célula

dados.mean() #7ª célula

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Columns: 293 entries, Unidade da Federação to Total
dtypes: float64(170), object(123)
memory usage: 61.9+ KB

<ipython-input-10-d7ddf7b68aba>:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  dados = pd.read_csv('/content/A150850189_28_143_208.csv', encoding='ISO-8859-1', skiprows=3, sep=';', skipfooter=12, thousands='.', decimal=',') #2ª célula
<ipython-input-10-d7ddf7b68aba>:13: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dados.mean() #7ª célula

2007/Ago       304952.77
2007/Set       788145.26
2007/Out      2440162.96
2007/Nov      5517354.05
2007/Dez     12337159.42
                ...
2021/Mai     87271862.20
2021/Jun     77590406.47
2021/Jul     60846287.01
2021/Ago     43885716.30
Total      6852320913.49
Length: 170, dtype: float64

In [11]:
dados.info

<bound method DataFrame.info of       Unidade da Federação  1992/Mar  1992/Abr  1993/Mai  1993/Dez  1994/Jan  \
0              11 Rondônia         -         -         -         -         -
1                  12 Acre         -         -         -         -         -
2              13 Amazonas         -         -         -         -         -
3               14 Roraima         -         -         -         -         -
4                  15 Pará         -         -         -         -         -
5                 16 Amapá         -         -         -         -         -
6             17 Tocantins         -         -         -         -         -
7              21 Maranhão         -         -         -         -         -
8                 22 Piauí         -         -         -         -         -
9                 23 Ceará         -         -         -         -         -
10  24 Rio Grande do Norte         -         -         -         -         -
11              25 Paraíba         -         -         -         -         -
12           26 Pernambuco         -         -         -         -         -
13              27 Alagoas         -         -         -         -         -
14              28 Sergipe         -         -         -         -         -
15                29 Bahia         -         -         -         -         -
16         31 Minas Gerais         -         -         -         -         -
17       32 Espírito Santo         -         -         -         -         -
18       33 Rio de Janeiro         -         -         -         -         -
19            35 São Paulo  40243.16  11449.99  34583.77  68556.52  39809.34
20               41 Paraná         -         -         -         -         -
21       42 Santa Catarina         -         -         -         -         -
22    43 Rio Grande do Sul         -         -         -         -         -
23   50 Mato Grosso do Sul         -         -         -         -         -
24          51 Mato Grosso         -         -         -         -         -
25                52 Goiás         -         -         -         -         -
26     53 Distrito Federal         -         -         -         -         -

    1994/Fev  1994/Mai  1994/Ago  1994/Nov  ...     2021/Jan     2021/Fev  \
0          -         -         -         -  ...  10045624.39  10677245.18
1          -         -         -         -  ...   4175526.06   5282655.42
2          -         -         -         -  ...  27406458.57  22341042.63
3          -         -         -         -  ...   3557821.99   4172285.82
4          -         -         -         -  ...  39042349.46  37113440.70
5          -         -         -         -  ...   2786277.13   2664375.13
6          -         -         -         -  ...   8868698.71   9098989.10
7          -         -         -         -  ...  31210354.69  35824653.31
8          -         -         -         -  ...  21839112.13  20414695.91
9          -         -         -         -  ...  57451589.31  60105521.76
10         -         -         -         -  ...  27452425.03  28344652.94
11         -         -         -         -  ...  21740778.25  23328004.56
12         -         -         -         -  ...  83144993.84  81741861.37
13         -         -         -         -  ...  20154290.67  21539842.43
14         -         -         -         -  ...  12765176.65  11742576.90
15         -         -         -         -  ...  88213804.44  96878079.79
16         -         -         -         -  ... 192844182.05 183891512.07
17         -         -         -         -  ...  40664905.15  39529966.31
18         -         -         -         -  ... 103468410.54  87518760.94
19  19904.67  19904.67  34532.40  23374.12  ... 361427087.80 352846447.86
20         -         -         -         -  ... 130532844.63 134077150.52
21         -         -         -         -  ...  75238574.26  82034122.92
22         -         -         -         -  ... 115991861.17 126730284.94
23         -         -         -         -  ...  24727004.66  25600761.42
24         -         -         -         -  ...  18889711.53  21544594.04
25         -         -         -         -  ...  42638703.48  45715467.93
26         -         -         -         -  ...  24484716.93  24156062.77

       2021/Mar     2021/Abr     2021/Mai     2021/Jun     2021/Jul  \
0   18147121.02  17753851.45  17659855.79  14435903.47  11834435.10
1    5699597.78   5002272.59   4326882.24   3458187.11   2302711.01
2   27923786.94  24515920.09  23973537.71  22175398.40  21614943.55
3    5427226.70   4192540.54   3681417.80   3475205.55   3320807.96
4   49625416.13  52558327.29  50907226.77  43876590.47  33718084.12
5    3960131.30   5153704.82   5672086.52   5469150.38   4136950.62
6   10129712.88   9762980.73  10161783.68   6349488.16   4610170.61
7   54315704.28  51797774.60  55324683.42  51958573.27  37775425.78
8   31586481.13  32367250.52  32550777.47  26015797.57  19972846.10
9   96063868.02 100543749.33 102825954.51  81919446.05  57727138.38
10  37147348.21  38411419.09  41819897.10  34438169.58  24537062.07
11  32197966.23  30904806.65  39602463.80  33149421.34  24925842.39
12 105871865.99 118218034.52 132095684.99 119545888.06  89156304.23
13  30875169.00  29413996.17  30550686.94  26888254.59  17475906.50
14  18750198.65  19136659.88  19720608.49  15007723.17   7751833.41
15 117816174.41 115928975.22 134229720.19 120516112.40  95691895.48
16 261376726.91 255545757.83 275151838.35 249713866.70 194734136.81
17  57618664.94  58031849.50  57345370.07  48137665.89  36550871.52
18 125735135.97 132965058.07 145372684.38 124909043.81 113660882.20
19 502905607.53 504427182.45 548112705.83 503160959.54 404373175.61
20 172636232.13 174040312.61 191861617.22 163580936.16 119408026.56
21  92581408.31  89976929.76 101661537.37  93055772.86  70531971.21
22 169687680.33 145302546.19 155084262.06 142812283.70 112805351.92
23  32506184.09  33101059.57  36885633.11  31595196.27  20711974.43
24  35790837.70  37534015.20  37859473.58  34937134.14  29364200.76
25  74464062.86  68630407.92  69467332.76  67162348.93  57891285.60
26  36391034.41  35641761.42  32434557.27  27196457.00  26265515.44

       2021/Ago      2021/Set          Total
0    7371334.84    1682801.60  1088059702.25
1    1196754.85             -   475290315.34
2   13806958.66    5292323.36  2061943006.93
3    2907871.07    1496814.75   352546288.71
4   20837865.89    4620263.03  4968811817.17
5    1875241.91     626751.41   337181964.14
6    2304080.49     312354.68  1110344733.46
7   25779674.83   11194657.20  4161325769.23
8   15220885.72    9371428.06  2450508593.82
9   35650007.47   16234603.93  7118540187.61
10  16809169.29    6055806.12  2867428082.03
11  16167879.55    8962429.99  2796673182.96
12  71625844.36   35603376.46  9243658123.01
13  11393875.70    5714532.94  2394793268.76
14   4636420.57    1509495.66  1313873341.39
15  61645689.06   24858284.14 10498497979.38
16 139157823.59   60010941.33 21899546392.60
17  27127454.08   11916897.69  3710941856.86
18  94137361.39   43133058.07 11131868548.73
19 301986341.98  130535317.64 44290790025.14
20  91187722.64   32660877.10 15672157558.11
21  48884998.15   18486461.58  8392938841.37
22  74954589.62   25200345.68 13613341350.00
23  11302985.98    2445267.12  2516383489.01
24  19849249.43    7325067.61  2386584382.72
25  44939821.34   18860370.17  5380179246.60
26  22156437.60   13173812.37  2778456616.77

[27 rows x 293 columns]>

In [12]:
dados.head()

,Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,2021/Set,Total
0,11 Rondônia,-,-,-,-,-,-,-,-,-,...,10045624.39,10677245.18,18147121.02,17753851.45,17659855.79,14435903.47,11834435.10,7371334.84,1682801.60,1088059702.25
1,12 Acre,-,-,-,-,-,-,-,-,-,...,4175526.06,5282655.42,5699597.78,5002272.59,4326882.24,3458187.11,2302711.01,1196754.85,-,475290315.34
2,13 Amazonas,-,-,-,-,-,-,-,-,-,...,27406458.57,22341042.63,27923786.94,24515920.09,23973537.71,22175398.40,21614943.55,13806958.66,5292323.36,2061943006.93
3,14 Roraima,-,-,-,-,-,-,-,-,-,...,3557821.99,4172285.82,5427226.70,4192540.54,3681417.80,3475205.55,3320807.96,2907871.07,1496814.75,352546288.71
4,15 Pará,-,-,-,-,-,-,-,-,-,...,39042349.46,37113440.70,49625416.13,52558327.29,50907226.77,43876590.47,33718084.12,20837865.89,4620263.03,4968811817.17

In [13]:
dados.tail()

,Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,2021/Set,Total
22,43 Rio Grande do Sul,-,-,-,-,-,-,-,-,-,...,115991861.17,126730284.94,169687680.33,145302546.19,155084262.06,142812283.70,112805351.92,74954589.62,25200345.68,13613341350.00
23,50 Mato Grosso do Sul,-,-,-,-,-,-,-,-,-,...,24727004.66,25600761.42,32506184.09,33101059.57,36885633.11,31595196.27,20711974.43,11302985.98,2445267.12,2516383489.01
24,51 Mato Grosso,-,-,-,-,-,-,-,-,-,...,18889711.53,21544594.04,35790837.70,37534015.20,37859473.58,34937134.14,29364200.76,19849249.43,7325067.61,2386584382.72
25,52 Goiás,-,-,-,-,-,-,-,-,-,...,42638703.48,45715467.93,74464062.86,68630407.92,69467332.76,67162348.93,57891285.60,44939821.34,18860370.17,5380179246.60
26,53 Distrito Federal,-,-,-,-,-,-,-,-,-,...,24484716.93,24156062.77,36391034.41,35641761.42,32434557.27,27196457.00,26265515.44,22156437.60,13173812.37,2778456616.77

In [14]:
dados.mean()

<ipython-input-14-99af3ba13e28>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dados.mean()

2007/Ago       304952.77
2007/Set       788145.26
2007/Out      2440162.96
2007/Nov      5517354.05
2007/Dez     12337159.42
                ...
2021/Mai     87271862.20
2021/Jun     77590406.47
2021/Jul     60846287.01
2021/Ago     43885716.30
Total      6852320913.49
Length: 170, dtype: float64